/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.xnews;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.Collections;

public class App {
    public String getGreeting() {
        return "Hello World from XNews!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        if (args.length < 1) {
            System.out.println("Please provide the file path as a command line argument.");
            return;
        }

        String filePath = args[0];

        try {
            List<UserPreference> userPreferences = readUserPreferences(filePath);
            userPreferences.forEach(System.out::println);

            NewsApiClient newsApiClient = new NewsApiClient();
            for (UserPreference userPreference : userPreferences) {
                String query = userPreference.getQuery();
                String language = userPreference.getLanguage();
                String sortBy = userPreference.getSortBy();
                List<NewsArticle> articles = newsApiClient.fetchNewsArticles(query, language, sortBy);
                System.out.println("News for " + userPreference.getName() + " (query: " + query + "):");
                System.out.println(articles.size());
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static List<UserPreference> readUserPreferences(String filePath) throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();
        UserPreference[] preferences = objectMapper.readValue(new File(filePath), UserPreference[].class);
        return Arrays.asList(preferences);
    }
}
